application: r-tree
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:    
- url: /style
  static_dir: style
- url: /scripts
  static_dir: scripts
  
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2                                                                  
  version: latest                                                               
- name: markupsafe                                                              
  version: latest
- name: django
  version: latest
